// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SistemaContas.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Manter conta")]
    public partial class ManterContaFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ManterContas.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Manter conta", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cadastrar uma conta")]
        [NUnit.Framework.CategoryAttribute("SemLogin")]
        public virtual void CadastrarUmaConta()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar uma conta", new string[] {
                        "SemLogin"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
testRunner.Given("que estou na página \"http://localhost:10941/Acesso/Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 6
testRunner.And("preencho o campo \"Usuario\" com o valor \"dansouza.95\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 7
testRunner.And("preencho o campo \"Senha\" com o valor \"01020300\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 8
testRunner.And("clico na opcao \"Entrar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
testRunner.Then("devo ver o elemento \"canvas\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 10
testRunner.And("clico na opcao \"MenuContas\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
testRunner.And("clico na opcao \"CadastrarConta\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
testRunner.Then("clico na opcao \"Credito\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 13
testRunner.And("preencho o campo \"CredorOuDevedor\" com o valor \"Cliente\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
testRunner.And("preencho o campo \"Descricao\" com o valor \"Prestação de serviços\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 15
testRunner.And("preencho o campo \"ValorConta\" com o valor \"150,00\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 16
testRunner.And("preencho o campo \"DataVencimento\" com o valor \"30/10/2014\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 17
testRunner.And("clico na opcao \"ValorConta\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 18
testRunner.When("clico na opcao \"btn_salvar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 19
testRunner.Then("devo ver o elemento \"table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
