// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SistemaContas.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Gerar relatórios do sistema")]
    public partial class GerarRelatoriosDoSistemaFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Relatorios.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Gerar relatórios do sistema", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Gerar um extrato em PDF dos últimos 7 dias")]
        [NUnit.Framework.CategoryAttribute("SemLogin")]
        public virtual void GerarUmExtratoEmPDFDosUltimos7Dias()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Gerar um extrato em PDF dos últimos 7 dias", new string[] {
                        "SemLogin"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
testRunner.Given("que estou na página \"http://localhost:10941/Acesso/Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 6
testRunner.And("preencho o campo \"Usuario\" com o valor \"dansouza.95\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 7
testRunner.And("preencho o campo \"Senha\" com o valor \"01020300\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 8
testRunner.And("clico na opcao \"Entrar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 9
testRunner.And("clico no link \"MenuRelatorios\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 10
testRunner.And("clico no link \"extrato7Dias\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
testRunner.And("clico na opcao \"btn_gerarExtrato\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
testRunner.And("clico no link \"Opcoes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
testRunner.And("clico no link \"Sair\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
testRunner.Then("devo ver o elemento \"input\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Gerar um extrato em PDF dos últimos 15 dias")]
        [NUnit.Framework.CategoryAttribute("SemLogin")]
        public virtual void GerarUmExtratoEmPDFDosUltimos15Dias()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Gerar um extrato em PDF dos últimos 15 dias", new string[] {
                        "SemLogin"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
testRunner.Given("que estou na página \"http://localhost:10941/Acesso/Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 19
testRunner.And("preencho o campo \"Usuario\" com o valor \"dansouza.95\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 20
testRunner.And("preencho o campo \"Senha\" com o valor \"01020300\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 21
testRunner.And("clico na opcao \"Entrar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 22
testRunner.And("clico no link \"MenuRelatorios\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 23
testRunner.And("clico no link \"extrato15Dias\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 24
testRunner.And("clico na opcao \"btn_gerarExtrato\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 25
testRunner.And("clico no link \"Opcoes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 26
testRunner.And("clico no link \"Sair\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 27
testRunner.Then("devo ver o elemento \"input\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Gerar um extrato em PDF dos últimos 30 dias")]
        [NUnit.Framework.CategoryAttribute("SemLogin")]
        public virtual void GerarUmExtratoEmPDFDosUltimos30Dias()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Gerar um extrato em PDF dos últimos 30 dias", new string[] {
                        "SemLogin"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
testRunner.Given("que estou na página \"http://localhost:10941/Acesso/Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 32
testRunner.And("preencho o campo \"Usuario\" com o valor \"dansouza.95\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 33
testRunner.And("preencho o campo \"Senha\" com o valor \"01020300\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 34
testRunner.And("clico na opcao \"Entrar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 35
testRunner.And("clico no link \"MenuRelatorios\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 36
testRunner.And("clico no link \"extrato30Dias\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 37
testRunner.And("clico na opcao \"btn_gerarExtrato\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 38
testRunner.And("clico no link \"Opcoes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 39
testRunner.And("clico no link \"Sair\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 40
testRunner.Then("devo ver o elemento \"input\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Gerar um extrato em PDF completo")]
        [NUnit.Framework.CategoryAttribute("SemLogin")]
        public virtual void GerarUmExtratoEmPDFCompleto()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Gerar um extrato em PDF completo", new string[] {
                        "SemLogin"});
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
testRunner.Given("que estou na página \"http://localhost:10941/Acesso/Login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 45
testRunner.And("preencho o campo \"Usuario\" com o valor \"dansouza.95\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 46
testRunner.And("preencho o campo \"Senha\" com o valor \"01020300\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 47
testRunner.And("clico na opcao \"Entrar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 48
testRunner.And("clico no link \"MenuRelatorios\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 49
testRunner.And("clico no link \"extratoCompleto\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 50
testRunner.And("clico na opcao \"btn_gerarExtrato\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 51
testRunner.And("clico no link \"Opcoes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 52
testRunner.And("clico no link \"Sair\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 53
testRunner.Then("devo ver o elemento \"input\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
